export type Car = {
  id: number;
  name: string;
  brand: string;
  category: "économique" | "berline" | "SUV" | "luxe" | "utilitaire";
  pricePerDay: number;
  seats: number;
  transmission: "Manuelle" | "Automatique";
  fuel: "Essence" | "Diesel" | "Hybride";
  year: number;
  mileage: string;
  image: string;
  features: string[];
  available: boolean;
  popular?: boolean;
};

export const cars: Car[] = [
  {
    id: 1,
    name: "Dacia Logan",
    brand: "Dacia",
    category: "économique",
    pricePerDay: 200,
    seats: 5,
    transmission: "Manuelle",
    fuel: "Diesel",
    year: 2023,
    mileage: "Kilométrage illimité",
    image: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
    features: ["Climatisation", "Bluetooth", "USB", "Radio"],
    available: true,
    popular: true,
  },
  {
    id: 2,
    name: "Renault Symbol",
    brand: "Renault",
    category: "économique",
    pricePerDay: 220,
    seats: 5,
    transmission: "Manuelle",
    fuel: "Essence",
    year: 2022,
    mileage: "Kilométrage illimité",
    image: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80",
    features: ["Climatisation", "Bluetooth", "Airbags"],
    available: true,
  },
  {
    id: 3,
    name: "Hyundai Tucson",
    brand: "Hyundai",
    category: "SUV",
    pricePerDay: 550,
    seats: 5,
    transmission: "Automatique",
    fuel: "Diesel",
    year: 2023,
    mileage: "Kilométrage illimité",
    image: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
    features: ["Climatisation", "GPS", "Caméra recul", "Bluetooth", "Siège chauffant"],
    available: true,
    popular: true,
  },
  {
    id: 4,
    name: "Volkswagen Polo",
    brand: "Volkswagen",
    category: "économique",
    pricePerDay: 280,
    seats: 5,
    transmission: "Manuelle",
    fuel: "Essence",
    year: 2023,
    mileage: "Kilométrage illimité",
    image: "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=800&q=80",
    features: ["Climatisation", "Bluetooth", "Airbags", "ABS"],
    available: true,
  },
  {
    id: 5,
    name: "Toyota Yaris",
    brand: "Toyota",
    category: "économique",
    pricePerDay: 250,
    seats: 5,
    transmission: "Manuelle",
    fuel: "Hybride",
    year: 2024,
    mileage: "Kilométrage illimité",
    image: "https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=800&q=80",
    features: ["Climatisation", "GPS", "Bluetooth", "USB"],
    available: true,
    popular: true,
  },
  {
    id: 6,
    name: "BMW Série 3",
    brand: "BMW",
    category: "luxe",
    pricePerDay: 900,
    seats: 5,
    transmission: "Automatique",
    fuel: "Diesel",
    year: 2023,
    mileage: "Kilométrage illimité",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
    features: ["Climatisation bi-zone", "GPS", "Cuir", "Bluetooth", "Toit ouvrant", "Parking auto"],
    available: true,
  },
  {
    id: 7,
    name: "Mercedes Classe C",
    brand: "Mercedes",
    category: "luxe",
    pricePerDay: 1100,
    seats: 5,
    transmission: "Automatique",
    fuel: "Essence",
    year: 2024,
    mileage: "Kilométrage illimité",
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
    features: ["Climatisation tri-zone", "GPS Premium", "Cuir", "Toit pano", "Massage", "Caméra 360"],
    available: false,
    popular: true,
  },
  {
    id: 8,
    name: "Ford Transit",
    brand: "Ford",
    category: "utilitaire",
    pricePerDay: 600,
    seats: 9,
    transmission: "Manuelle",
    fuel: "Diesel",
    year: 2022,
    mileage: "Kilométrage illimité",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    features: ["Climatisation", "GPS", "Radio", "Grandes portes"],
    available: true,
  },
  {
    id: 9,
    name: "Kia Sportage",
    brand: "Kia",
    category: "SUV",
    pricePerDay: 480,
    seats: 5,
    transmission: "Automatique",
    fuel: "Diesel",
    year: 2023,
    mileage: "Kilométrage illimité",
    image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80",
    features: ["Climatisation", "GPS", "Caméra recul", "Bluetooth"],
    available: true,
  },
];

export const categories = ["Tous", "économique", "berline", "SUV", "luxe", "utilitaire"] as const;
